### ISSUE TITLE
Update electron?

### ISSUE THREAD

**Issue by keithah** [dalinaum/IRCCloud#13]
I would love to see updated builds with the latest electron! It solves many memory leaks plaguing the app.

**Comment by kinghat** [comment]
i see the electron version has been updated, would it be possible to get new builds?

**Comment by dalinaum** [comment]
It seems #14 resolve this. I'll release the new version during the year end.

**Comment by dalinaum** [comment]
https://github.com/dalinaum/IRCCloud/releases/tag/v0.9 resolved this. I'll close this issue.
