### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by outsideris** [dalinaum/IRCCloud#3]
Recognizable app icon is better than electron's default icon.

How about:
- http://www.iconarchive.com/show/ios7-style-metro-ui-icons-by-igh0zt/MetroUI-Apps-iCloud-icon.html
- https://www.iconfinder.com/icons/386602/cloud_app_cloudapp_icon

**Comment by dalinaum** [comment]
Looks good. Are they royalty-free icons?

**Comment by outsideris** [comment]
First one's license - Free for non-commercial use.
Second one's licence is CC BY 3.0.

I think license is ok, but I'm not sure because irccloud is commercial serverce.
But this project is non-commercial. :)

**Comment by dalinaum** [comment]
Thanks @outsideris

**Comment by dalinaum** [comment]
https://github.com/dalinaum/IRCCloud/releases/tag/v0.7

**Comment by outsideris** [comment]
Good!!!
